config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^login/$', TemplateView.as_view(template_name='account/login.html'), name='login'),
    url(r'^signup/$', TemplateView.as_view(template_name='account/signup.html'), name='signup'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^help/$', TemplateView.as_view(template_name='pages/help.html'), name='help'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('washd.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

washd/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

washd/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255, null=True)
    firstName = models.CharField(max_length=70, null=True)
    lastName = models.CharField(max_length=70, null=True)
    USER_TYPES = (
        ('D', 'Dirty'),
        ('W', 'Washr')
    )
    type = models.CharField(max_length=1, choices=USER_TYPES, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})


class Addresses(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.CharField(max_length=200, null=True)
    city = models.TextField(null=True)
    state = models.TextField(null=True)
    zipCode = models.TextField(null=True)
    locationName = models.CharField(max_length=50, null=True)


class PaymentAccount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(null=True)

washd/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

washd/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

washd/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Washd{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css"
          integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/flexslider.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/lightbox.min.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/ytplayer.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/theme-startup.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="{% static 'css/theme-startup.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400%7CRaleway:100,400,300,500,600,700%7COpen+Sans:400,500,600' rel='stylesheet' type='text/css'>

    {% endblock %}

  </head>

  <body>

    {% include 'header.html' %}

    {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
    {% endif %}

    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}

    {% block modal %}{% endblock modal %}

    {% include 'footer.html' %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
    <!-- Required by Bootstrap v4 Alpha 4 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"
            integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js"
            integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js"
            integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU"
            crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->

    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/flickr.js' %}"></script>
    <script src="{% static 'js/flexslider.min.js' %}"></script>
    <script src="{% static 'js/lightbox.min.js' %}"></script>
    <script src="{% static 'js/masonry.min.js' %}"></script>
    <script src="{% static 'js/twitterfetcher.min.js' %}"></script>
    <script src="{% static 'js/spectragram.min.js' %}"></script>
    <script src="{% static 'js/ytplayer.min.js' %}"></script>
    <script src="{% static 'js/countdown.min.js' %}"></script>
    <script src="{% static 'js/smooth-scroll.min.js' %}"></script>
    <script src="{% static 'js/parallax.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

    {% endblock javascript %}
  </body>
</html>

washd/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

washd/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

washd/templates/footer.html
{% load staticfiles i18n %}
<footer class="footer-1 bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <div class="widget">
          <img alt="Logo" class="logo" src="{% static 'img/logo-light.png' %}"/>
          <hr>
          <ul class="link-list social-list">
            <li><a href="/about">About</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Careers</a></li>
            <li><a href="#">Press</a></li>
            <li><a href="#">Site Map</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="widget">
          <h6 class="title">Discover</h6>
          <hr>
          <ul class="link-list social-list">
            <li><a href="#">How It Works</a></li>
            <li><a href="#">Become a Driver</a>
            <li>
            <li><a href="#">Invite Friends</a></li>
          </ul>
        </div>
        <!--end of widget-->
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="widget">
          <h6 class="title">Support</h6>
          <hr>
          <ul class="link-list social-list">
            <li><a href="/help">Help</a></li>
            <li><a href="#">Trust & Safety</a></li>
            <li><a href="#">Terms & Privacy</a></li>
            <li><a href="#">Policies</a></li>
          </ul>
        </div>
        <!--end of widget-->
      </div>
      <div class="col-md-3 col-sm-6">
        <div class="widget">
          <h6 class="title">Get In Touch</h6>
          <hr>
          <ul class="link-list social-list">
            <li>
              <a href="https://www.facebook.com/Washd-1830886003859756/" target="_blank"><i class="ti-facebook"></i>
                Facebook</a>
            </li>
            <li>
              <a href="https://www.instagram.com/washdapp/" target="_blank"><i class="ti-instagram"></i> Instagram</a>
            </li>
            <li>
              <a href="https://twitter.com/washdapp" target="_blank"><i class="ti-twitter-alt"></i> Twitter</a>
            </li>
          </ul>
        </div>
        <!--end of widget-->
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 text-center">
        <span class="sub">&copy; 2016 Washd, LLC. All rights reserved.</span>
      </div>
    </div>
  </div>
  <!--end of container-->
  <a class="btn btn-sm fade-half back-to-top inner-link" href="#top">Top</a>
</footer>

washd/templates/header.html
{% load staticfiles i18n %}
<div class="nav-container">
  <a id="top"></a>
  <nav>
    <div class="nav-bar">
      <div class="module left">
        <a href="/">
          <img class="logo logo-light" alt="Folded" src="{% static 'img/logo-light.png' %}"/>
          <img class="logo logo-dark" alt="Folded" src="{% static 'img/logo-dark.png' %}"/>
        </a>
      </div>
      <div class="module widget-handle mobile-toggle right visible-sm visible-xs">
        <i class="ti-menu"></i>
      </div>
      <div class="module-group right">
        <div class="module left">
          <ul class="menu">
            <!-- <li>
                <a href="#">
                    Find a City
                </a>
            </li> -->
            <li>
              <a href="/help">
                Help
              </a>
            </li>
            <li>
              <a href="/login">
                Sign In
              </a>
            </li>
            <li>
              <a class="btn btn-sm home-register" href="/signup">Register</a>
            </li>
          </ul>
        </div>
      </div>
      <!--end of module group-->
    </div>
  </nav>
</div>

washd/templates/pages/about.html
{% extends "base.html" %}

{% block title %}Folded - About{% endblock title %}

{% block content %}
<div class="main-container">
            <section class="page-title page-title-4 bg-secondary">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6">
                            <h3 class="uppercase mb0">About Washd</h3>
                        </div>
                        <div class="col-md-6 text-right">
                            <ol class="breadcrumb breadcrumb-2">
                                <li>
                                    <a href="/">Home</a>
                                </li>
                                <li class="active">About</li>
                            </ol>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                          About Text Here...
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>

            <hr class="mb0">
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="uppercase">
                                <strong>Life At Washd</strong>
                            </h5>
                        </div>
                        <div class="col-md-9">
                            <div class="instafeed grid-gallery" data-user-name="washdapp">
                                <ul></ul>
                            </div>
                        </div>
                    </div>
                    <!--end of row-->
                </div>
                <!--end of container-->
            </section>
  </div>
{% endblock content %}

washd/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

washd/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

washd/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}